FROM alanfranz/fwd-ubuntu-precise:latest
MAINTAINER Alan Franzoni <username@franzoni.eu>
RUN apt-get -y update
RUN apt-get -y dist-upgrade
RUN apt-get -y install rsync ruby1.9.3
RUN gem1.9.3 install rake bundler
